# Ref: https://github.com/docker/build-push-action#usage
name: Build Docker container - Ko Ko Ye

on:
  push:
    branches:
      - development
      - master

env:
  DOCKER_IMAGE_NAME: kokoye2007/open-event-server

jobs:
  docker:
    if: ${{ github.repository_owner == 'kokoye2007' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            kokoye2007/open-event-server
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

